### PR TITLE
Add Algolia remark

### PR DESCRIPTION
**Pull request by Carlgo11**
Algolia requires open source projects to in some way display on the page that Algolia provides the search functionality. I think this way is a non-intrusive way of doing that.

>In exchange for using Algolia for free, we ask that you place a small "Search by Algolia" logo in your search results or on your site where people can see it. The logo should link to [https://algolia.com](https://www.algolia.com/).

Source: https://www.algolia.com/for-open-source/

## Screenshots
Unfocused:

Focused:

### CODE REVIEW

**Comment by phallobst** [comment]
When I tested this locally, the `/algolia.svg` image got a 404 (so the link is there, but invisible). I checked with `hugo --renderToDisk`, but the file was not present inside the target directory. Not sure if something is missing or wrong on my side... :man_shrugging:

**Comment by Carlgo11** [comment]
That's very odd. I cloned the branch again and it works for me.
What hugo version is that? I don't see a --renderToDisk argument for hugo 0.110.0.
I used the following build script:
```SH
#!/usr/bin/env sh

# Generate content
echo "Generating content"
ruby scripts/generate_entries.rb &
ruby scripts/generate_regions.rb &
wait

# Build site
echo "Building static site"
hugo serve
```
https://user-images.githubusercontent.com/3535780/216844766-9083dac4-3748-4570-975b-9d06e5e55836.mp4

**Comment by phallobst** [comment]
I had version 0.92.0 before - now I installed version 0.110.0 and get this error when building:

`Error building site: [...] execute of template failed: template: partials/regions.html:3:12: executing "partials/regions.html" at <sort . "name">: error calling sort: sequence must be provided`

Weird...

**Comment by Carlgo11** [comment]
I had a similar issue earlier. Solves it by running `scripts/generate_entries.rb` and `scripts/generate_regions.rb`.

**Review by phallobst — APPROVED** [review]

**Pull request merged**
